# Production Docker-Compose mit Registry Image
version: '3.8'

services:
  discord-bot:
    # Verwende das frisch gebaute Registry Image
    image: ghcr.io/bottrapper/discord-bot:main
    container_name: discord-bot-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/bot.db
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
